name: OSSF Scorecard Weekly

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ossf-scorecard:
    # To write a badge
    permissions:
      id-token: write
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Run analysis
        uses: ossf/scorecard-action@05b42c624433fc40578a4040d5cf5e36ddca8cde # v2.4.2
        with:
          publish_results: true
          results_file: ossf_scorecard.json
          results_format: json
